version: '3'

networks: 
    laravel:


services: 
    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
        depends_on: 
            - mysql
            - php
        networks: 
            - laravel

    mysql:
        image: mysql:latest
        container_name: mysql 
        # restart: no
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
           MYSQL_DATABASE: laravel
           MYSQL_USER: root
           MYSQL_ROOT_PASSWORD: root
            # MSYQL_ALLOW_EMPTY_PASSWORD:
           SERVICE_TAG: dev
           SERVICES_NAME: mysql
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel 
    
    npm:
        image: node:13.7
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
